Sni support
twitter/finagle pull request #607
Opened 2017-04-11 15:07 UTC by koshelev

Depends on https://github.com/twitter/finagle/pull/603. Would appreciate a feedback, if this a right direction and what are possible improvements.

Problem

The server name indication is not supported by theNetty4ServerSslHandler at the moment.

Solution

- Netty4SniHandler is implemented. It delays channelActive event  till server_name is processed and than replaces itself with  SslHandler.
- Netty4ServerSslHandler adds the Netty4SniHandler to the pipeline  if SniParameter is available.

2017-04-13 19:14 UTC, ryanoneill commented
Hi @koshelev, thank you for the pull request. I wanted to let you know that I have looked at the code, and am going to ask for you to make some changes. I am currently thinking about how to fit this within the structure of not only where the code is now, but where it's going as well. I should have a better answer for you with concrete things to change tomorrow (Friday). Thanks.

2017-04-13 19:46 UTC, koshelev commented
Hi @ryanoneill. Sure, I see the current code in the PR as just a starting point for a discussion and will be happy to improve it. Looking forward to your suggestions!

2017-04-21 18:52 UTC, koshelev commented
Hi @ryanoneill, any idea when you will have a time to review this PR?

2017-05-09 21:52 UTC, mosesn commented
LGTM from my perspective, but @ryanoneill is the ultimate authority here

2017-05-09 21:52 UTC, ryanoneill commented
Hi @koshelev, sorry for the long delay. I'm going to take another look now and see how we can best incorporate this.

2017-05-10 01:04 UTC, ryanoneill commented
There's a lot of great work here, thank you. I sincerely apologize for the delay. I hadn't looked much into SNI Matching on the server side within Netty before, so I had some items to look into. 

Some of the changes included in this PR have already made it into Finagle which is great, so thank you. I have some suggestions on how to make further changes which would allow us to accept this PR as part of Finagle. If you're interested in working through them, that's great. If not, I'll probably continue this on as time permits with you getting the credit for it.

In this version, `Netty4SniHandler` is extending [SniHandler](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SniHandler.java), which requires a mapping of type `AsyncMapping[String, SslContext]`. This value is passed in via the Finagle stack param that you added which also turns this functionality on. 

We prefer to limit the exposure of Netty specific types in Finagle APIs, especially after the amount of effort required to update from Netty 3 to Netty 4 in Finagle. Also, this uses Netty's `SslContext`, which we don't expose and only use contained within `Netty4ClientEngineFactory` and `Netty4ServerEngineFactory`. 

If we use Netty's `SniHandler`, we're locked into using that `AsyncMapping[String, SslContext]`, which I think is a non-starter for us. After looking at the implementation of `SniHandler` though, I think we can make everything work well by instead extending [AbstractSniHandler](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/AbstractSniHandler.java). `AbstractSniHandler` does all of the protocol work, and it would also allow us to use our own types there.

I would prefer if the mapping were along the lines of `Map[String, SslServerConfiguration]`, and then `Netty4SniHandler` used the `Netty4ServerEngineFactory` along with the specific `SslServerConfiguration` to create an `Engine` that's used with the `SslHandler`. That would be more in line with how engine creation and configuration works in Finagle today.

We can then expand on that in the future beyond `Map[String, SslServerConfiguration]` to incorporate different `SslServerEngineFactory` values if necessary.

Would that work for you for what you're trying to do? Let me know your thoughts when you have an opportunity. Thanks again.

2017-05-10 22:41 UTC, ryanoneill requested changes
Changes requested via comment on the pull request.

2017-05-17 12:24 UTC, koshelev commented
@ryanoneill Thanks a lot for your feedback! I'm on vacation now and will be able to work on the PR again next week.

2017-05-17 18:06 UTC, ryanoneill commented
@koshelev Hope you're enjoying your vacation! Glad to hear that you're interested in pursuing this.

2017-07-21 23:01 UTC, nepthar commented
@koshelev Have you had a chance to take a look at this recently?

2017-07-24 06:42 UTC, koshelev commented
@netphar Unfortunately found no time :(. Will try to find time this or next week.

2017-08-01 15:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/twitter/finagle?pullRequest=607) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/twitter/finagle?pullRequest=607) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/twitter/finagle?pullRequest=607) it.</sub>

2017-08-01 15:34 UTC, koshelev commented
@ryanoneill I finally found some time to work on this PR again. Could you please have a look and let me know WDYT?

2017-08-07 18:41 UTC, ryanoneill commented
@koshelev I'm going to take another look at this now. Thanks for following up.

2017-08-15 12:05 UTC, koshelev commented
@ryanoneill have you had a chance to check the PR?

2017-08-15 20:58 UTC, ryanoneill commented
@koshelev I have not, I'm sorry. I'm going to take a thorough look now.

2017-08-15 23:19 UTC, ryanoneill requested changes
Thank you for your perseverance here @koshelev. I feel like this is really close. With the changes suggested, I believe we would be ready to pull this in and put it up for review internally.

2017-08-15 23:19 UTC, ryanoneill commented on finagle-core/src/main/scala/com/twitter/finagle/ssl/KeyCredentials.scala
> +    extends KeyCredentials
Undo this change please. If you would like to add this outside the context of this pull request, we can discuss it in a separate PR.

2017-08-15 23:19 UTC, ryanoneill commented on finagle-core/src/main/scala/com/twitter/finagle/ssl/SslConfigurations.scala
> +      case KeyCredentials.KeyAndCertChain(key, certChain) =>
Undo this change please. If you would like to add this outside the context of this pull request, we can discuss it in a separate PR.

2017-08-15 23:19 UTC, ryanoneill commented on finagle-core/src/main/scala/com/twitter/finagle/ssl/SslConfigurations.scala
> +      case TrustCredentials.Certificates(certs) =>
Undo this change please. If you would like to add this outside the context of this pull request, we can discuss it in a separate PR.

2017-08-15 23:19 UTC, ryanoneill commented on finagle-core/src/main/scala/com/twitter/finagle/ssl/TrustCredentials.scala
> +  case class Certificates(certs: Array[X509Certificate]) extends TrustCredentials
Undo this change please. If you would like to add this outside the context of this pull request, we can discuss it in a separate PR.

2017-08-15 23:19 UTC, ryanoneill commented on finagle-netty4/src/main/scala/com/twitter/finagle/netty4/ssl/server/Netty4ServerSslHandler.scala
> +final case class SniSupport(mapping: SniSupport.ServerNameToContext)
Please move this to a file named `SniSupport.scala` in the same directory.

2017-08-15 23:19 UTC, ryanoneill commented on finagle-netty4/src/main/scala/com/twitter/finagle/netty4/ssl/server/Netty4ServerSslHandler.scala
> +final case class SniSupport(mapping: SniSupport.ServerNameToContext)
For `mapping`, I believe we should use `Option[Map[String, SslServerConfiguration]]` instead.
None means the parameter is off.
Some(sniMapping) is a mapping from hostnames to SslServerConfigurations

2017-08-15 23:19 UTC, ryanoneill commented on finagle-netty4/src/main/scala/com/twitter/finagle/netty4/ssl/server/Netty4ServerSslHandler.scala
> +  type ServerNameToContext = String => TwitterFuture[Option[SslServerConfiguration]]
Remove

2017-08-15 23:19 UTC, ryanoneill commented on finagle-netty4/src/main/scala/com/twitter/finagle/netty4/ssl/server/Netty4ServerSslHandler.scala
> +  implicit val param: Stack.Param[SniSupport] = Stack.Param(SniSupport( (_: String) => {
implicit val param: Stack.Param[SniSupport] = Stack.Param(SniSupport(None))

2017-08-15 23:19 UTC, ryanoneill commented on finagle-netty4/src/main/scala/com/twitter/finagle/netty4/ssl/server/Netty4ServerSslHandler.scala
> +  val DenialSslContext = {
private[ssl]

2017-08-15 23:19 UTC, ryanoneill commented on finagle-netty4/src/main/scala/com/twitter/finagle/netty4/ssl/server/Netty4ServerSslHandler.scala
> +  def fromOption(mapping: String => Option[SslServerConfiguration]): SniSupport = SniSupport((serverName: String) => {
Remove

2017-08-15 23:19 UTC, ryanoneill commented on finagle-netty4/src/main/scala/com/twitter/finagle/netty4/ssl/server/Netty4ServerSslHandler.scala
> +  private[this] def addSniHandler(channel: Channel, factory: SslServerEngineFactory): Unit = {
private[this] def addSniHandler(
      channel: Channel,
      factory: SslServerEngineFactory,
      sniMapping: Map[String, SslServerConfiguration]
    ): Unit = {
      ...
    }

2017-08-15 23:19 UTC, ryanoneill commented on finagle-netty4/src/main/scala/com/twitter/finagle/netty4/ssl/server/Netty4ServerSslHandler.scala
> +      if( params.contains[SniSupport] ) {
val SniSupport(mapping) = params[SniSupport]

    mapping match {
      case Some(sniMapping) =>
        addSniHandler(ch, factory, sniMapping)
      case None => 
        ...
    }

2017-08-15 23:19 UTC, ryanoneill commented on finagle-netty4/src/main/scala/com/twitter/finagle/netty4/ssl/server/Netty4SniHandler.scala
> +import io.netty.util.concurrent.{Future, Promise}
Please make this Future => NettyFuture. Since it's the Twitter codebase, Future within it almost always means Twitter Future.

2017-08-15 23:19 UTC, ryanoneill commented on finagle-netty4/src/main/scala/com/twitter/finagle/netty4/ssl/server/Netty4SniHandler.scala
> +class Netty4SniHandler(mapping: SniSupport.ServerNameToContext, factory: SslServerEngineFactory,
mapping: Map[String, SslServerConfiguration]

2017-08-15 23:19 UTC, ryanoneill commented on finagle-netty4/src/main/scala/com/twitter/finagle/netty4/ssl/server/Netty4SniHandler.scala
> +    mapping(hostname).respond {
promise.setSuccess(mapping.get(hostname))

2017-08-15 23:19 UTC, ryanoneill commented on finagle-netty4/src/test/scala/com/twitter/finagle/netty4/Netty4SslTest.scala
> +        keyCredentials = KeyCredentials.KeyAndCertChain(serverCert.key(), Array(serverCert.cert())),
keyCredentials = KeyCredentials.CertAndKey(serverCert.certificate(), serverCert.privateKey()),
    trustCredentials = TrustCredentials.CertCollection(clientCert.certificate())

2017-08-15 23:19 UTC, ryanoneill commented on finagle-netty4/src/test/scala/com/twitter/finagle/netty4/Netty4SslTest.scala
> +        SniSupport.fromOption(serverCerts.get(_).map(mkConfig)))
SniSupport(Some(serverCerts.mapValues(mkConfig)))

2017-08-15 23:19 UTC, ryanoneill commented on finagle-netty4/src/test/scala/com/twitter/finagle/netty4/Netty4SslTest.scala
> +      mkClient(serverCrt.cert(), Some(hostname))
Change mkClient to just take hostname: String instead of hostname: Option[String] here, so that it's not necessary to calling hostname.get later.

2017-08-15 23:19 UTC, ryanoneill commented on finagle-netty4/src/test/scala/com/twitter/finagle/netty4/Netty4SslTest.scala
> +      Await.ready(ctx.close(), 30.seconds)
30 seconds seems much too long, please reduce.

2017-08-15 23:19 UTC, ryanoneill commented on finagle-netty4/src/test/scala/com/twitter/finagle/netty4/Netty4SslTest.scala
> +    assert(response == "OK\n")
This test failed for me until I removed the newline.

2017-08-15 23:19 UTC, ryanoneill commented on finagle-netty4/src/test/scala/com/twitter/finagle/netty4/Netty4SslTest.scala
> +    val response = Await.result(ctx.client("security is overrated!\n"), 300.seconds)
Please change from 300 seconds to something more reasonable.

2017-08-16 15:00 UTC, koshelev commented on finagle-netty4/src/main/scala/com/twitter/finagle/netty4/ssl/server/Netty4ServerSslHandler.scala
> +final case class SniSupport(mapping: SniSupport.ServerNameToContext)
`String => TwitterFuture[Option[SslServerConfiguration]]` is more flexible, IMO. `Option[Map[String, SslServerConfiguration]]` implies the mapping is static and keys and certificates are available locally. For instance, it is not true in our case. We have keys and certificates stored in [Vault](https://www.vaultproject.io/) and new servers can be added at any time. That is why I also added https://github.com/twitter/finagle/pull/607/files/61cd8d956037e0efadcb186e48a54790b2c55802#diff-7be4dc145c09c1df2647a7ee1cc8bccd

2017-08-17 15:44 UTC, koshelev commented on finagle-netty4/src/main/scala/com/twitter/finagle/netty4/ssl/server/Netty4ServerSslHandler.scala
> +final case class SniSupport(mapping: SniSupport.ServerNameToContext)
@ryanoneill WDYT?

2018-03-20 19:05 UTC, adleong commented
What is the status of this PR?  I'm very excited about SNI support in Finagle, is this still being worked on?

2018-07-11 16:07 UTC, bryce-anderson commented
I'm closing this because it's been inactive for nearly a year. From the history, it looks like it was really close and may be worth picking back up. If that is the case, feel free to reopen this and get it merged with `develop`.

2018-07-11 16:07 UTC, closed without merging